# Generated by Django 4.2.4 on 2023-10-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingadress',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
