# Generated by Django 4.1.7 on 2023-12-22 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_order_purchase_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='purchase_count',
        ),
    ]
