# Generated by Django 4.1.7 on 2023-12-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_order_purchase_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
