# Generated by Django 4.2.4 on 2023-11-23 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_productreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
