"""
Django settings for webbanhang project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path





# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
  # Đặt thành False khi bạn muốn chuyển sang môi trường sản phẩm



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!a^alx^igdshm*nf96=vy=!s_1&4^0pgt6q8^!qa#!rl@xpb#d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django_light',
    'admin_tools_stats',
    'jazzmin',  # this must be BEFORE 'admin_tools' and 'django.contrib.admin'
    'django_nvd3',
    # 'admin_material.apps.AdminMaterialDashboardConfig',
    # 'admin_tools',
    # 'admin_tools.theming',
    # 'admin_tools.menu',
    # 'admin_tools.dashboard',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
   
    'app',
    'paypal.standard.ipn',
    'paypal',


]
PAYPAL_CLIENT_ID = 'AU7f0bOaJ5WyOQZhkTVJV8EEuLLK_oPJmvy7lVUktOsj89lWaEiGcIxKN0w_FT4L1arb3CLecj-z_o3h'
PAYPAL_SECRET_KEY = 'EOhPJnIg7--IuICXIJ_cltuRbuv_YVHNVwU8xABE12IZDo6MAicijmrxmjmIsTdyaax9d71-yGPC-T0b'
PAYPAL_RECEIVER_EMAIL = "sb-yx1ss27954293@business.example.com"
PAYPAL_TEST = True  # Set False khi triển khai ở môi trường production
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'webbanhang.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'webbanhang.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "minhhieu1",
        "USER": "root",
        "PASSWORD": "",
        "HOST": "localhost",
        "PORT": "3306",
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'djongo',
#         'ENFORCE_SCHEMA': False,
#         'CLIENT': {
#             'host': 'mongodb://thangpro9669:thangthanG1@ac-m1qaccg-shard-00-00.0uxofn3.mongodb.net:27017,ac-m1qaccg-shard-00-01.0uxofn3.mongodb.net:27017,ac-m1qaccg-shard-00-02.0uxofn3.mongodb.net:27017/?ssl=true&replicaSet=atlas-y0t9di-shard-0&authSource=admin&retryWrites=true&w=majority',
#         }
#     }
# }



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# LOGIN_REDIRECT_URL = '/admin'
#     # EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
STATICFILES_DIRS=[
    os.path.join(BASE_DIR,'static')
]
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'collected_static')

MEDIA_URL='/images/'
MEDIA_ROOT=os.path.join(BASE_DIR,'app/static/images')

JAZZMIN_SETTINGS = {

    #############
    # Side Menu #
    #############

    # Whether to display the side menu
   "show_sidebar": True,

    # Whether to auto-expand the menu
    "navigation_expanded": True,

    # Hide these apps when generating the side menu e.g (auth)
   "hide_apps": [],

    # Hide these models when generating the side menu (e.g., auth.user)
   "hide_models": [],

    # List of apps (and/or models) to base side menu ordering off of (does not need to contain all apps/models)
   "order_with_respect_to": ["auth", "app"],  # Add your app name here

    # Custom links to append to app groups, keyed on app name
    # "custom_links": {
    #     "app": [
    #         {
    #             "name": "Your Chart",
    #             "url": "admin_tools_stats/",
    #             "icon": "fa fa-chart-line",  # Use an appropriate icon class
    #             "permissions": [],  # Add necessary permissions
    #         }
    #     ]
    # },
}
